include:
  - project: 'devops/ci'
    file: 
      - 'common.yml'

variables:
    PROJECT_TYPE: frontend

tce_check_ng:
  rules:
    - when: never

test_karma:
  rules:
    - when: never

lint_tslint:
  rules:
    - when: never

docs_frontend:
  rules:
    - when: never